openapi: 3.0.4
info:
  title: Flykit apis

paths:
  /login:
    post:
      tags:
        - auth
      summary: Realiza login do usuário
      description: Realiza login e retorna o token de autenticação.
      operationId: loginUser
      requestBody:
        description: Dados de login
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 6
      responses:
        '200':
          description: Login realizado com sucesso
        '401':
          description: Credenciais inválidas
        default:
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /profile:
    get:
      tags:
        - auth
      summary: Retorna o perfil do usuário autenticado
      description: Retorna informações do usuário autenticado.
      operationId: getProfile
      responses:
        '200':
          description: Perfil retornado com sucesso
        '401':
          description: Não autenticado

  /v1/order:
    post:
      tags:
        - order
      summary: Cria um novo pedido
      description: Cria um novo pedido no sistema.
      operationId: createOrder
      requestBody:
        description: Dados do pedido
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: integer
                requesterName:
                  type: string
                destination:
                  type: string
                departureDate:
                  type: string
                  format: date
                arrivalDate:
                  type: string
                  format: date
                status:
                  type: string
                  enum: [approved, requested, cancelled]
      responses:
        '201':
          description: Pedido criado com sucesso
        '400':
          description: Dados inválidos
        default:
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    get:
      tags:
        - order
      summary: Lista todos os pedidos
      description: Retorna uma lista de pedidos filtrados.
      operationId: listOrders
      parameters:
        - name: departureDate
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: arrivalDate
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: destination
          in: query
          required: false
          schema:
            type: string
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [approved, requested, cancelled]
      responses:
        '200':
          description: Lista de pedidos
        default:
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/order/{orderId}:
    get:
      tags:
        - order
      summary: Detalha um pedido
      description: Retorna os detalhes de um pedido específico.
      operationId: getOrder
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Pedido encontrado
        '404':
          description: Pedido não encontrado
        default:
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      tags:
        - order
      summary: Atualiza o status de um pedido
      description: Atualiza o status de um pedido específico.
      operationId: updateOrder
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Dados para atualização do pedido
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [approved, requested, cancelled]
      responses:
        '200':
          description: Pedido atualizado com sucesso
        '400':
          description: Dados inválidos
        '404':
          description: Pedido não encontrado
        default:
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message