name: Build Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: cp -rf backend/docker/Dockerfile . && docker build -t hyperf .

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: backend/composer install

      - name: Run Unit Tests
        run: backend/composer test
