name: Build Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: cp -rf backend/docker/Dockerfile . && docker build -t hyperf .

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
          extensions: swoole, openswoole, mbstring, json, pdo, xml, curl, zip, bcmath, pcntl, posix, sockets, intl, fileinfo, sodium, redis
          coverage: xdebug

      - name: Install Dependencies
        working-directory: ./backend
        run: composer install

      - name: Run Unit Tests
        working-directory: ./backend
        run: composer test
